SELECT DISTINCT ?subjektLabel ?propertyLabel ?objektLabel ?subjekt ?property ?objekt WHERE {
  
  # 1. Zentrales Register aller Himmelskörper (Verhindert Fehl-Matches durch Namensgleichheit)
  VALUES (?subjekt ?sLabel) {
    (wd:Q525 "Sun") (wd:Q308 "Mercury") (wd:Q313 "Venus") (wd:Q2 "Earth")
    (wd:Q111 "Mars") (wd:Q319 "Jupiter") (wd:Q193 "Saturn") (wd:Q324 "Uranus")
    (wd:Q332 "Neptune") (wd:Q339 "Pluto")
    (wd:Q405 "Moon") (wd:Q3123 "Io") (wd:Q3143 "Europa") (wd:Q3169 "Ganymede")
    (wd:Q3134 "Callisto") (wd:Q2565 "Titan") (wd:Q3303 "Enceladus")
    (wd:Q3359 "Triton") (wd:Q6604 "Charon") (wd:Q102694 "Nix") (wd:Q102701 "Hydra")
  }

  {
    # Zweig A: Physikalische Kennzahlen (Masse/Radius)
    # Nutzt direkte Pfade für maximale Geschwindigkeit
    {
      ?subjekt p:P2067 [ psv:P2067 [ wikibase:quantityAmount ?amt; wikibase:quantityUnit [rdfs:label ?unit] ] ].
      BIND("Mass" AS ?propertyLabel) BIND(wdt:P2067 AS ?property)
    }
    UNION
    {
      ?subjekt p:P2120 [ psv:P2120 [ wikibase:quantityAmount ?amt; wikibase:quantityUnit [rdfs:label ?unit] ] ].
      BIND("Radius" AS ?propertyLabel) BIND(wdt:P2120 AS ?property)
    }
    FILTER(LANG(?unit) = "en")
    BIND(CONCAT(STR(?amt), " ", ?unit) AS ?objektLabel)
    BIND(?sLabel AS ?subjektLabel)
  }
  UNION
  {
    # Zweig B: Dynamische Missionssuche (COSPAR-gefiltert für Performance)
    ?mission wdt:P247 ?cospar. # Filtert sofort auf Raumsonden (extrem schnell)
    ?mission wdt:P18 ?image.   # Bild als Relevanz-Indikator
    
    {
      { ?mission wdt:P3896 ?subjekt. BIND("destination" AS ?propertyLabel) }
      UNION
      { ?mission wdt:P1158 ?subjekt. BIND("landing site" AS ?propertyLabel) }
      UNION
      { ?mission p:P793 [ ps:P793 ?event ; pq:P642 ?subjekt ] . BIND("significant event" AS ?propertyLabel) }
    }
    
    ?mission rdfs:label ?objektLabel. FILTER(LANG(?objektLabel) = "en")
    BIND(?mission AS ?objekt)
    BIND(?sLabel AS ?subjektLabel)
  }
  UNION
  {
    # Zweig C: Hierarchische Verbindungen (Sonne -> Planet -> Mond)
    VALUES (?subjekt ?objekt ?propertyLabel) {
      (wd:Q525 wd:Q308 "planet") (wd:Q525 wd:Q313 "planet") (wd:Q525 wd:Q2 "planet")
      (wd:Q525 wd:Q111 "planet") (wd:Q525 wd:Q319 "planet") (wd:Q525 wd:Q193 "planet")
      (wd:Q525 wd:Q324 "planet") (wd:Q525 wd:Q332 "planet") (wd:Q525 wd:Q339 "planet")
      (wd:Q2 wd:Q405 "moon") (wd:Q319 wd:Q3123 "moon") (wd:Q319 wd:Q3143 "moon")
      (wd:Q319 wd:Q3169 "moon") (wd:Q319 wd:Q3134 "moon") (wd:Q193 wd:Q2565 "moon")
      (wd:Q193 wd:Q3303 "moon") (wd:Q332 wd:Q3359 "moon") (wd:Q339 wd:Q6604 "moon")
      (wd:Q339 wd:Q102694 "moon") (wd:Q339 wd:Q102701 "moon")
    }
    # Objekt-Labels für Monde/Planeten auflösen
    ?objekt rdfs:label ?objektLabel. FILTER(LANG(?objektLabel) = "en")
    BIND(?sLabel AS ?subjektLabel)
  }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY ?subjektLabel

SELECT DISTINCT ?planet ?planetLabel ?mission ?missionLabel ?property ?propertyLabel ?launchDate WHERE {
  # IDs der Planeten aus data.csv
  VALUES ?planet { 
    wd:Q308 # Merkur
    wd:Q313 # Venus
    wd:Q111 # Mars
    wd:Q319 # Jupiter
    wd:Q193 # Saturn
    wd:Q324 # Uranus
    wd:Q332 # Neptun
  }
  
  # Suche nach Missionen und identifiziere die P-ID der Verbindung
  { 
    ?mission wdt:P1158 ?planet. 
    BIND(wdt:P1158 AS ?property). 
  } UNION { 
    ?mission wdt:P376 ?planet. 
    BIND(wdt:P376 AS ?property). 
  } UNION { 
    ?planet wdt:P2581 ?mission. 
    BIND(wdt:P2581 AS ?property). 
  }
  
  # Startdatum der Mission (P619)
  OPTIONAL { ?mission wdt:P619 ?launchDate. }
  
  # Labels für alle Q- und P-Werte abrufen
  SERVICE wikibase:label { bd:serviceParam wikibase:language "de,en". }
} ORDER BY ?planetLabel ?launchDate
