#query
SELECT DISTINCT
?i_item1 ?i_item1Label ?i_item1Description ?ii_item1 ?iu_item1
?rn_relation1Label (?rn_relation1Label AS ?rc_relation1Label)
?i_item2 ?i_item2Label ?i_item2Description ?ii_item2 ?iu_item2
WHERE {

  VALUES ?i_item1 { wd:Q544 }   # Solar System

  ?rn_relation1 wikibase:directClaim wdt:P527 .

  VALUES ?i_item2 {
    wd:Q525        # Sun
    wd:Q7879772    # inner Solar System
    wd:Q3962257    # outer Solar System
  }

  wd:Q544 wdt:P527 ?i_item2 .

  OPTIONAL { ?i_item1 wdt:P18 ?ii_item1. }
  OPTIONAL { ?i_item2 wdt:P18 ?ii_item2. }
  OPTIONAL { ?iu_item1 schema:about ?i_item1; schema:isPartOf <https://en.wikipedia.org/>. }
  OPTIONAL { ?iu_item2 schema:about ?i_item2; schema:isPartOf <https://en.wikipedia.org/>. }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en". }
}

#query
SELECT DISTINCT
?i_item1 ?i_item1Label ?i_item1Description ?ii_item1 ?iu_item1
?rn_relation1Label (?rn_relation1Label AS ?rc_relation1Label)
?i_item2 ?i_item2Label ?i_item2Description ?ii_item2 ?iu_item2
WHERE {

  VALUES ?i_item1 { wd:Q7879772 }   # inner Solar System

  ?rn_relation1 wikibase:directClaim wdt:P527 .

  VALUES ?i_item2 {
    wd:Q308   # Mercury
    wd:Q313   # Venus
    wd:Q2     # Earth
    wd:Q111   # Mars
  }

  wd:Q7879772 wdt:P527 ?i_item2 .

  OPTIONAL { ?i_item1 wdt:P18 ?ii_item1. }
  OPTIONAL { ?i_item2 wdt:P18 ?ii_item2. }
  OPTIONAL { ?iu_item1 schema:about ?i_item1; schema:isPartOf <https://en.wikipedia.org/>. }
  OPTIONAL { ?iu_item2 schema:about ?i_item2; schema:isPartOf <https://en.wikipedia.org/>. }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en". }
}

#query
SELECT DISTINCT
?i_item1 ?i_item1Label ?i_item1Description ?ii_item1 ?iu_item1
?rn_relation1Label (?rn_relation1Label AS ?rc_relation1Label)
?i_item2 ?i_item2Label ?i_item2Description ?ii_item2 ?iu_item2
WHERE {

  VALUES ?i_item1 { wd:Q3962257 }   # outer Solar System

  ?rn_relation1 wikibase:directClaim wdt:P527 .

  VALUES ?i_item2 {
    wd:Q319   # Jupiter
    wd:Q193   # Saturn
    wd:Q324   # Uranus
    wd:Q332   # Neptune
  }

  wd:Q3962257 wdt:P527 ?i_item2 .

  OPTIONAL { ?i_item1 wdt:P18 ?ii_item1. }
  OPTIONAL { ?i_item2 wdt:P18 ?ii_item2. }
  OPTIONAL { ?iu_item1 schema:about ?i_item1; schema:isPartOf <https://en.wikipedia.org/>. }
  OPTIONAL { ?iu_item2 schema:about ?i_item2; schema:isPartOf <https://en.wikipedia.org/>. }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],de,en". }
}