SELECT ?i_influencedByPerson ?i_influencedByPersonLabel ?i_influencedByPersonDescription ?ii_influencedByPerson ?iu_influencedByPerson ?rn_influences ?i_person ?i_personLabel ?i_personDescription ?ii_person ?iu_person ?rn_t_DateOfBirthLabel ?ic_DateOfBirth ?rn_t_DateOfDeathLabel ?ic_DateOfDeath ?rn_NotableWorkLabel ?i_NotableWork ?i_NotableWorkLabel ?i_NotableWorkDescription ?ic_NotableWork ?iu_NotableWork ?ii_NotableWork
WHERE 
{
  ?i_person wdt:P737* wd:Q159481.
  ?i_person wdt:P31 wd:Q5.
  ?i_person wdt:P737 ?i_influencedByPerson.
  ?i_influencedByPerson wdt:P31 wd:Q5.
  OPTIONAL { ?i_person wdt:P18 ?ii_person. }
  BIND (CONCAT (STR (?i_person), "§if") AS ?iu_person).
  OPTIONAL { ?i_influencedByPerson wdt:P18 ?ii_influencedByPerson. }
  BIND (CONCAT (STR (?i_influencedByPerson), "§if") AS ?iu_influencedByPerson).
  BIND("influences" AS ?rn_influences).
  OPTIONAL { ?i_influencedByPerson wdt:P569 ?ic_DateOfBirth.
             ?rn_t_DateOfBirth wikibase:directClaim wdt:P569.
           }
  OPTIONAL { ?i_influencedByPerson wdt:P570 ?ic_DateOfDeath.
             ?rn_t_DateOfDeath wikibase:directClaim wdt:P570.
           }
  OPTIONAL { ?i_influencedByPerson wdt:P800 ?i_NotableWork.
             BIND (CONCAT (STR (?i_NotableWork), "§if") AS ?iu_NotableWork).
             ?rn_NotableWork wikibase:directClaim wdt:P800.
             OPTIONAL { ?i_NotableWork wdt:P18 ?ii_NotableWork. }
           }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
