SELECT ?i_influencer ?i_influencerLabel ?i_influencerDescription ?iu_influencer ?ii_influencer ?rn_influences ?i_influenced ?rn_t_DateOfBirthLabel ?ic_DateOfBirth ?rn_t_DateOfDeathLabel ?ic_DateOfDeath ?rn_presentInWorkLabel ?i_presentInWork ?i_presentInWorkLabel ?i_presentInWorkDescription ?iu_presentInWork ?ii_presentInWork ?rn_significantEventLabel ?i_significantEvent ?i_significantEventLabel ?i_significantEventDescription ?iu_significantEvent ?ii_significantEvent WHERE {

  {
    SELECT ?i_influencer WHERE {
      { ?i_influencer (wdt:P737|wdt:P802) wd:Q302. }
      UNION
      { wd:Q302 (wdt:P737|wdt:P802) ?i_influencer. }
      UNION
      { BIND (wd:Q302 AS ?i_influencer) }
    }
  }

  OPTIONAL { ?i_influenced (wdt:P737|wdt:P802) ?i_influencer. }

  BIND (CONCAT (STR (?i_influencer), "§if") AS ?iu_influencer).

  OPTIONAL { ?i_influencer wdt:P18 ?ii_influencer. }

  BIND("student" AS ?rn_influences).

  OPTIONAL {
              ?i_influencer wdt:P569 ?ic_DateOfBirth.
              ?rn_t_DateOfBirth wikibase:directClaim wdt:P569.
           }

  FILTER NOT EXISTS {
                      ?i_influencer wdt:P569 ?DateOfBirth.
                      FILTER (?DateOfBirth < ?ic_DateOfBirth).
                    }

  OPTIONAL {
             ?i_influencer wdt:P570 ?ic_DateOfDeath.
             ?rn_t_DateOfDeath wikibase:directClaim wdt:P570.
           }

  FILTER NOT EXISTS {
                      ?i_influencer wdt:P570 ?DateOfDeath.
                      FILTER (?DateOfDeath < ?ic_DateOfDeath).
                    }

  OPTIONAL {
             ?i_influencer wdt:P1441 ?i_presentInWork.
             BIND (CONCAT (STR (?i_presentInWork), "§if") AS ?iu_presentInWork).
             ?rn_presentInWork wikibase:directClaim wdt:P1441.
             OPTIONAL { ?i_presentInWork wdt:P18 ?ii_presentInWork. }
           }

  OPTIONAL {
             ?i_influencer wdt:P793 ?i_significantEvent.
             BIND (CONCAT (STR (?i_significantEvent), "§if") AS ?iu_significantEvent).
             ?rn_significantEvent wikibase:directClaim wdt:P793.
             OPTIONAL { ?i_significantEvent wdt:P18 ?ii_significantEvent. }
           }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,de,fr". }
}
