#query
SELECT ?i_Occupation ?ic_Occupation ?i_OccupationLabel ?i_GeneralizedOccupation ?ic__Occupation ?i_GeneralizedOccupationLabel
WHERE 
{
  ?i_Occupation (wdt:P279*) wd:Q169470.
  ?i_Occupation wdt:P279 ?i_GeneralizedOccupation.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

#query
SELECT ?i_priceWinner ?i_priceWinnerLabel ?ii_PriceWinnerPic ?i_occupation ?ic_occupation ?i_occupationLabel ?i_occupationDescription ?rn_t_DateOfBirthLabel ?ic_DateOfBirth ?rn_t_DateOfDeathLabel ?ic_DateOfDeath (year(?NobelPriceYear) as ?i_NobelPriceYear) ?ic_NobelPriceYear
WHERE 
{
  ?i_priceWinner wdt:P166 wd:Q38104.
  ?i_priceWinner wdt:P106 ?i_occupation.
  ?i_priceWinner p:P166 ?statement.
  ?statement ps:P166 wd:Q38104.
  ?statement pq:P585 ?NobelPriceYear.
  OPTIONAL { ?i_priceWinner wdt:P18 ?ii_PriceWinnerPic. }
  OPTIONAL { ?i_priceWinner wdt:P569 ?ic_DateOfBirth. }
  OPTIONAL { ?rn_t_DateOfBirth wikibase:directClaim wdt:P569. }
  OPTIONAL { ?i_priceWinner wdt:P570 ?ic_DateOfDeath. }
  OPTIONAL { ?rn_t_DateOfDeath wikibase:directClaim wdt:P570. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
